name: CI Workflow

# Run the workflow on any push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK (example for a Java project)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Install dependencies (example for a Node.js project)
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test

      # Build the application
      - name: Build project
        run: npm run build

      # Upload artifacts (optional, for Java projects, e.g., to save JAR files)
      - name: Upload JAR file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: my-app
          path: path/to/build-artifact.jar  # replace with your actual path

  # Deploy job (optional)
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        run: |
          echo "Deploying application..."
          # Add your deployment steps here (e.g., SSH commands, cloud deployment CLI, etc.)
